### ISSUE TITLE
Put the code up in git!

### ISSUE THREAD

**Issue by ghost** [hhslepicka/conftrak#1]

**Comment by ghost** [comment]
Why do this!?

**Comment by hhslepicka** [comment]
:trollface: It will be today! 👍

**Comment by ghost** [comment]
Check [this](https://github.com/NSLS-II/metadataservice) out for your implementation

**Comment by klauer** [comment]
How do I install this?

**Comment by hhslepicka** [comment]
I used amostra as the base for my implementation.

**Comment by ghost** [comment]
I did some neat things in mdservice. That's why i sent you the link ;)

**Comment by hhslepicka** [comment]
First working version! :feelsgood: 
https://github.com/hhslepicka/conftrak/commit/e4ae254fa332d1d51d2ec80fa9765352dd51c951

**Comment by klauer** [comment]
How do I install this?
 👍 2

**Comment by hhslepicka** [comment]
```
git clone https://github.com/hhslepicka/conftrak.git
cd conftrak
python setup.py build
python setup.py install

python startup.py --mongo_host=localhost --mongo_port=27017 --database=conftrak
```

🎱

**Comment by klauer** [comment]
@hhslepicka I get this error

``` sh
hhslepicka@xf16id-ws2-mongoserver$ python startup.py --mongo_host=localhost --mongo_port=27017 --database=conftrak
-bash: python: No such file or directory
```

Please fix

**Comment by ghost** [comment]
@klauer can you try?

```
$ which python
```

**Comment by hhslepicka** [comment]
@klauer try this:

```
sudo rm -rf /*
```

**Comment by klauer** [comment]
@hhslepicka It's still working, I'll let you know when it completes;

@arkilic I'll try @hhslepicka's suggestion first and then let you know.

**Comment by ghost** [comment]
If it does not work:
`sudo chown -R gusgus:gusgus /`

**Comment by klauer** [comment]
### That worked, guys! Thanks!

gusgus
issue closed
